/* **********
AUTHOR: Clint MacDonald 100######
DATE: June 17, 2021
TITLE: Week 5 - PART 2 - Continued,
DESCRIPTION: AutoNumbering, Temp Tables
*/

-- continuing from last class

CREATE TABLE icCustomers (
    customerID NUMBER(5) PRIMARY KEY,
    rewardCardNumber CHAR(6),
    balance NUMBER(8,2) DEFAULT(0) NOT NULL,
    CONSTRAINT people_customers_FK FOREIGN KEY (customerID)
        REFERENCES icPeople(personID)
);

CREATE TABLE icEmployees (
    employeeID NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY 
        PRIMARY KEY,
    sin INT UNIQUE
);

CREATE TABLE icOrders (
    orderID INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    orderDate DATE NOT NULL,
    isPaid NUMBER(3) DEFAULT(0),
    employeeID NUMBER(5),
    customerID NUMBER(5),
    CONSTRAINT icOrder_PK PRIMARY KEY(orderID),
    CONSTRAINT order_employee_FK FOREIGN KEY (employeeID) REFERENCES icEmployees(employeeID),
    CONSTRAINT order_customer_FK FOREIGN KEY (customerID) REFERENCES icCustomers(customerID),
    CONSTRAINT isPaid_CHK CHECK (isPaid BETWEEN 0 and 1)
);

ALTER TABLE icOrderItems 
    ADD CONSTRAINT orderItems_order_FK FOREIGN KEY (orderID) 
        REFERENCES icOrders(orderID);

DELETE FROM icCustomers;
INSERT INTO icCustomers (customerID, rewardCardNumber) 
    VALUES (2, 'A3S2W4');
INSERT INTO icEmployees VALUES (1, 123456789); 

INSERT INTO icOrders VALUES (NULL, sysdate, 1, 1, 2);
INSERT INTO icOrders VALUES (5, sysdate, 1, 1, 2);
INSERT INTO icOrders VALUES (NULL, sysdate, 1, 1, 2);

INSERT INTO icOrders (orderDate, isPaid, customerID, employeeID)
    VALUES (TO_DATE('06-16-21','mm-dd-yy'), 0, 2, 1);
    
-- TEMP TABLES
CREATE TABLE tempEmployees AS
    SELECT  EmployeeNumber AS empID,
            lastname, firstname, 
            firstName || ' ' || lastname AS fullName,
            email, officecode, 
            reportsto, jobtitle
    FROM employees
    WHERE EmployeeNumber < 2000;
    
CREATE TABLE tempCustomers AS
    SELECT * FROM customers;
    
CREATE TABLE tempCustomers2 AS
    SELECT * FROM customers WHERE customerNumber < 0;

CREATE TABLE icTempOrders AS
    SELECT * FROM icOrders;
    
DELETE FROM icOrders;

INSERT INTO icOrders SELECT * FROM icTempOrders;


---------------------
SELECT * FROM ALL_OBJECTS
    ORDER BY owner;

SELECT * FROM ALL_OBJECTS
    WHERE owner LIKE '%212D%'